dwindle_test = executable(
	'test-dwindle',
	'dwindle.c',
	include_directories: sway_inc,
)

test('dwindle', dwindle_test)

dynamic_resize_test = executable(
	'test-dynamic-resize',
	'dynamic_resize.c',
	include_directories: sway_inc,
)

test('dynamic-resize', dynamic_resize_test)

pointer_motion_test = executable(
	'test-pointer-motion',
	'pointer_motion.c',
	include_directories: sway_inc,
)

test('pointer-motion', pointer_motion_test)

tag_test = executable(
	'test-tag',
	'tag.c',
	include_directories: sway_inc,
)

test('tag', tag_test)

window_class_test = executable(
	'test-window-class',
	'window_class.c',
	include_directories: sway_inc,
)

test('window-class', window_class_test)
